# Generated by Django 6.0.5 on 2026-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0040_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='camera_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='gaming_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
